# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rahul/Documents/secret_sharing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rahul/Documents/secret_sharing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rahul/Documents/secret_sharing/CMakeFiles /Users/rahul/Documents/secret_sharing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rahul/Documents/secret_sharing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named secret_sharing

# Build rule for target.
secret_sharing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 secret_sharing
.PHONY : secret_sharing

# fast build rule for target.
secret_sharing/fast:
	$(MAKE) -f CMakeFiles/secret_sharing.dir/build.make CMakeFiles/secret_sharing.dir/build
.PHONY : secret_sharing/fast

GF2_8LookupTable.o: GF2_8LookupTable.cpp.o

.PHONY : GF2_8LookupTable.o

# target to build an object file
GF2_8LookupTable.cpp.o:
	$(MAKE) -f CMakeFiles/secret_sharing.dir/build.make CMakeFiles/secret_sharing.dir/GF2_8LookupTable.cpp.o
.PHONY : GF2_8LookupTable.cpp.o

GF2_8LookupTable.i: GF2_8LookupTable.cpp.i

.PHONY : GF2_8LookupTable.i

# target to preprocess a source file
GF2_8LookupTable.cpp.i:
	$(MAKE) -f CMakeFiles/secret_sharing.dir/build.make CMakeFiles/secret_sharing.dir/GF2_8LookupTable.cpp.i
.PHONY : GF2_8LookupTable.cpp.i

GF2_8LookupTable.s: GF2_8LookupTable.cpp.s

.PHONY : GF2_8LookupTable.s

# target to generate assembly for a file
GF2_8LookupTable.cpp.s:
	$(MAKE) -f CMakeFiles/secret_sharing.dir/build.make CMakeFiles/secret_sharing.dir/GF2_8LookupTable.cpp.s
.PHONY : GF2_8LookupTable.cpp.s

TemplateField.o: TemplateField.cpp.o

.PHONY : TemplateField.o

# target to build an object file
TemplateField.cpp.o:
	$(MAKE) -f CMakeFiles/secret_sharing.dir/build.make CMakeFiles/secret_sharing.dir/TemplateField.cpp.o
.PHONY : TemplateField.cpp.o

TemplateField.i: TemplateField.cpp.i

.PHONY : TemplateField.i

# target to preprocess a source file
TemplateField.cpp.i:
	$(MAKE) -f CMakeFiles/secret_sharing.dir/build.make CMakeFiles/secret_sharing.dir/TemplateField.cpp.i
.PHONY : TemplateField.cpp.i

TemplateField.s: TemplateField.cpp.s

.PHONY : TemplateField.s

# target to generate assembly for a file
TemplateField.cpp.s:
	$(MAKE) -f CMakeFiles/secret_sharing.dir/build.make CMakeFiles/secret_sharing.dir/TemplateField.cpp.s
.PHONY : TemplateField.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/secret_sharing.dir/build.make CMakeFiles/secret_sharing.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/secret_sharing.dir/build.make CMakeFiles/secret_sharing.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/secret_sharing.dir/build.make CMakeFiles/secret_sharing.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... secret_sharing"
	@echo "... GF2_8LookupTable.o"
	@echo "... GF2_8LookupTable.i"
	@echo "... GF2_8LookupTable.s"
	@echo "... TemplateField.o"
	@echo "... TemplateField.i"
	@echo "... TemplateField.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

